# NumPy Arrays

In [1]:
my_list=[1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.36790123, 0.36507483, 0.37922598, 0.86891794, 0.12533121])

In [20]:
np.random.rand(5,5)

array([[0.90083816, 0.19578124, 0.4485703 , 0.30189433, 0.43565244],
       [0.51904771, 0.15976188, 0.60257682, 0.91887876, 0.56988629],
       [0.91908512, 0.27973422, 0.2176745 , 0.5875921 , 0.76272117],
       [0.52280478, 0.98549285, 0.39176048, 0.67207128, 0.15926925],
       [0.76246549, 0.3922222 , 0.98941107, 0.05284532, 0.26971325]])

In [21]:
np.random.randn(2)

array([ 1.85813038, -2.47486309])

In [22]:
np.random.randn(4,4)

array([[-1.31398774, -1.81230449,  0.21408632, -0.43661312],
       [-1.71464161, -1.31365961,  0.18983173,  0.7162153 ],
       [ 0.08817267, -1.01499087, -1.61765319,  1.1626833 ],
       [-0.13086416, -0.25929027, -1.84068437, -0.25662505]])

In [23]:
np.random.randint(1,100)

45

In [24]:
np.random.randint(1,100,10)

array([ 9, 90, 36, 15, 97, 48, 40, 99, 88, 20])

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr = np.random.randint(0,50,10)

In [29]:
ranarr

array([35, 19, 12,  3, 14, 45, 30, 46,  1, 38])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr.max()

46

In [32]:
ranarr.min()

1

In [33]:
ranarr.argmax()

7

In [34]:
ranarr.argmin()

8

In [35]:
arr.shape

(25,)

In [36]:
arr = arr.reshape(5,5)

In [37]:
arr.shape

(5, 5)

In [38]:
arr.dtype

dtype('int64')

# NumPy Indexing and Selection

In [39]:
import numpy as np

In [40]:
arr = np.arange(0,11)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[8]

8

In [43]:
arr[1:5]

array([1, 2, 3, 4])

In [44]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [45]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [46]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
arr[0:5] = 100

In [48]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [49]:
arr = np.arange(0,11)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
slice_of_arr = arr[0:6]

In [52]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [53]:
slice_of_arr[:] = 99

In [54]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [55]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
arr_copy = arr.copy()

In [57]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [58]:
arr_copy[:] = 100

In [59]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [60]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [61]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [62]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [63]:
arr_2d[0][0]

5

In [64]:
arr_2d[0]

array([ 5, 10, 15])

In [65]:
arr_2d[1][1]

25

In [66]:
arr_2d[2][1]

40

In [67]:
arr_2d[2,1]

40

In [68]:
arr_2d[1,2]

30

In [70]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [71]:
arr = np.arange(1,11)

In [72]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [75]:
bool_arr = arr > 5

In [76]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [77]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [78]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [79]:
arr[arr<3]

array([1, 2])

In [80]:
arr_2d = np.arange(50).reshape(5,10)

In [81]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [82]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# NumPy Operations

* **Array with Array**
* **Array with Sclalars**
* **Universal Array Functions**

In [83]:
import numpy as np

In [85]:
arr = np.arange(0,10)

In [86]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [88]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [89]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [90]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [91]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91])

In [92]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [93]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [94]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [95]:
np.max(arr)

9

In [96]:
arr.max()

9

In [97]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])